# Generated by Django 4.1.7 on 2023-05-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="write",
            new_name="writer",
        ),
    ]
