# Generated by Django 4.1.7 on 2023-05-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0002_rename_write_article_writer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
